### ISSUE TITLE
Expectations of overseas students 

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/charter#13]
How will we balance our commitment to diversity and welcoming people from all cultures with our need for contributions from students after the course has finished?

So, if someone comes from abroad and is only able to stay for the duration of the course before returning home, we've effectively lost any chance of their contributing to the next FAC.

How do we feel about this?

**Comment by sofer** [comment]
@rub1e I don't have an answer to this yet, but I agree that it is an interesting question to raise.

**Comment by nelsonic** [comment]
agreed. good question. to which my answer is: _build a_ **_Remote Working Culture**_ so that _anyone_ can participate/contribute from _anywhere_. 
Contributing back to FAC is a _lot_ more than _mentoring_ in the space. Simply having the _chat_ open and answering questions is a great place to start. But others are: 
- commenting on people's code
- raising issues that guide people toward learning opportunities
- writing content (e.g blog posts) which can increase (FAC's) visibility in the media. 
- mentoring _other_ people in the location where the person is from ... start a group in their local library where people can meet up and learn "_Creative Tech_" together (_the FAC origin story..._) :wink:

**Comment by iteles** [comment]
@joshpitzalis is a great example of this, as he's now running coding programmes/clubs with kids in India under the F&C banner!
