### ISSUE TITLE
*When* is a FAC member?

### ISSUE THREAD

**Issue by minaorangina** [foundersandcoders/charter#14]
Does FAC membership refer to the post 16-week period, or does it kick in after the 8th(/10th) week?  The latter half of the course is often a time that those who are interested in employment may start looking around.  

Let's say FAC membership officially begins after week 16.  If one student were uninterested in FAC membership and finds a job in week 13, and a second student was fine with FAC membership and also finds a job, how would we handle this?  Are they both expected to go through FAC recruitment even though this would _technically_ still be the pre-membership teaching period?

**Comment by iteles** [comment]
Very good point here @minaorangina, this **definitely** needs clarification in the readme as it's something we're likely to encounter often.

My understanding from conversations with @sofer is that this is something that is expected of students from the second they walk through FAC doors (i.e. if they find a job in week 7 based on the promise of finishing the course, this would also apply to them).

Assigning to @sofer for clarification in the readme.

**Comment by sofer** [comment]
@minaorangina I am not sure that the question of _When?_ can really be answered until we answer the question raised by @iteles of _What?_ #9 and also _Who?_.

Membership started as something that was conferred on everyone who came with us from Camden Town at the end of last year. It has also been something that has automatically been thrust upon successive cohorts from FAC4 on. It has been suggested more than once at meetings that anyone who is interested should be able to apply for it. Then, for a couple of months, it was something associated with a £50 annual subscription.

I don't know if you had a chance to look at #10, but what I am most concerned about is making clear to _students_ (rather than _members_) what our expectation are of them before they accept a place on the course, which the original wording of the charter did not make at all clear.

**Comment by iteles** [comment]
:+1: I'm already working on the basis of #10, I think that's the most important issue open right now!
