### ISSUE TITLE
This rule makes me uneasy. I don't want to involve FAC in my conversations with prospective employers.

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/charter#24]
I'm not sure we need this.

**Comment by sofer** [comment]
:+1:

**Comment by rub1e** [comment]
I know what you mean, but I like it for two reasons:
- It leaves the reader in no doubt whatsoever that this is a condition of joining. I know this is said explicitly more than once, but it's an important point  
- It's very likely the reader will have that exact thought as she makes her way through the document

**Comment by msmichellegar** [comment]
I like it too.

**Comment by sofer** [comment]
OK. I think the reason to take it out is that if people are not yet uneasy about this, then offering the suggestion that they perhaps should be, might needlessly make them uneasy, but I do not have strong feelings either way. In any case, I have added it back and created a pull request. @izaakrogan could you offer a counter-argument or merge and close the issue: https://github.com/foundersandcoders/charter/pull/26

Thank you all.

**Comment by iteles** [comment]
I would suggest that a _re-wording_ of the issue to frame it in a more positive light might suffice. I haven't had a chance to re-word myself yet, but thoughts are welcome!

**Comment by rub1e** [comment]
I've done a pull request on top of that pull request: #28 

My suggestion here is to let the "uneasy" question back in so there is at least a placeholder for all of the content, but then reword it when we can

@iteles can I just check - is it the question, the answer, or both that you think negative (not disagreeing, just checking (with respect!))? Cos I think the question itself is spot on (maybe "I'm not sure about" rather than "I don't want"), but it's the answer that can be softened. 

Thoughts?

**Comment by sofer** [comment]
As discussion on this has gone quiet and we are discussing the document at the meeting tomorrow, I have merged @rub1e's changes into v3 and then merged both his and my changes back into master.
